### ISSUE TITLE
create_config.py not generating a correct config.yaml file!

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#33]
Current output of `create_config.py`:
```
config:
  BinderHub:
    image_prefix: /<prefix>-
    use_registry: true
hub:
  url: http://<jupyterhub_ip>
```
Should be:
```
config:
  BinderHub:
    image_prefix: <docker_id> OR <docker_org>/<prefix>-
    use_registry: true
    hub_url: http://<>jupyterhub_ip
```
