### ISSUE TITLE
Docker ID parsed as null in deploy.sh container mode

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#42]
When the BinderHub is deployed, we're getting internal server errors due to the Docker ID not being parsed correctly to `config.yaml`.

Plan is to replace the python scripts `create_config.py` and `create_secret.py` with `sed` commands in `deploy.sh`. Then test the DOCKER_ORG `if` statement.

### Update

Changing python scripts for sed commands worked, but docker username is still being parsed as `null` to `config.yaml`.

Required:
```
config:
  BinderHub:
    use_registry: true
    image_prefix: dockerid/binder-dev-
```

Returned:
```
config:
  BinderHub:
    use_registry: true
    image_prefix: null/binder-dev-
```
