### ISSUE TITLE
BinderHub connected to an ACR does not pull images, just rebuilds them

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/binderhub-deploy#55]
In PR #53, I'm working on a deployment script that gives users a choice between using DockerHub or an Azure Container Registry (ACR) to store the images built by repo2docker/BinderHub. See [`deploy_acr.sh`](https://github.com/alan-turing-institute/binderhub-deploy/blob/feature/acr/acr/deploy_acr.sh).

The deployment script works fine (with the exception of one or two `sed` bugs). However when launching Binder instances, the BinderHub chooses to rebuild and push a new image rather than pull an existing image from the ACR.

This is surprising since, by design, if the cluster has permission to write to the ACR then it _definitely_ has permissions to read from it (see [here](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#acrpush)). So why isn't it?

Any ideas @trallard? @betatim is there anyone in the Binder community who's familiar with Azure (other than me!)?

**Comment by sgibson91** [comment]
`config.yaml` template:
```
config:
  BinderHub:
    use_registry: true
    image_prefix: <acr-login-server>/<prefix>-
    hub_url: http://<jupyterhub-ip>
  DockerRegistry:
    token_url: "https://<acr-login-server>/oauth2/token?service=<acr-login-server>"

jupyterhub:
  hub:
    imagePullSecret:
      enabled: true
      registry: <acr-login-server>
      username: <username>  # this is the Azure service principal app ID
      password: <password>  # this is the Azure service principal app key
```

`secret.yaml` template:
```
jupyterhub:
  hub:
    services:
      binder:
        apiToken: "<apiToken>"
  proxy:
    secretToken: "<secretToken>"

registry:
  url: https://<acr-login-server>
  username: <username>  # same as config.yaml
  password: <password>  # same as config.yaml
```
